name: Ci Pipelines

on:
  push:
    paths-ignore:
      - "**/*.md"

jobs:
  buid-and-test:
    strategy:
      matrix:
        node: [16.x] # add more e.g: 18.x 20.x 22.x
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3

        with:
          node-version: ${{matrix.node}}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
